### ISSUE TITLE
Are Leetcode Solutions Allowed ? 

### ISSUE THREAD

**Issue by Recognizeyourself** [hasthamalp/learn-coding#9]

**Comment by hasthamalp** [comment]
Hi,  @Recognizeyourself Thanks for reaching out . Try to code yourself. Leetcode solutions are also allowed ..

**Comment by Recognizeyourself** [comment]
Thanks For replying. On it !!

**Comment by hasthamalp** [comment]
Happy Contributing... @Recognizeyourself
